language: go

os:
  - linux
  - osx

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - master

install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
